modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/gigaherz/Enderthing/issues" #optional
displayURL="https://github.com/gigaherz/Enderthing" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[mods]] #mandatory
modId="enderthing" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Enderthing" #mandatory
#updateJSONURL="http://myurl.me/"
description='''
Shared inventories with chests and keys
'''

[[dependencies.enderthing]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"